//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.AboutPage
{
	using System; 

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class AboutPage { }
#else

	public class AboutPage : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public AboutPage()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/Foodler;component/SampleData/AboutPage/AboutPage.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private string _AboutTabLabel = string.Empty;

		public string AboutTabLabel
		{
			get
			{
				return this._AboutTabLabel;
			}

			set
			{
				if (this._AboutTabLabel != value)
				{
					this._AboutTabLabel = value;
					this.OnPropertyChanged("AboutTabLabel");
				}
			}
		}

		private string _VersionLabel = string.Empty;

		public string VersionLabel
		{
			get
			{
				return this._VersionLabel;
			}

			set
			{
				if (this._VersionLabel != value)
				{
					this._VersionLabel = value;
					this.OnPropertyChanged("VersionLabel");
				}
			}
		}

		private string _DescriptionLabel = string.Empty;

		public string DescriptionLabel
		{
			get
			{
				return this._DescriptionLabel;
			}

			set
			{
				if (this._DescriptionLabel != value)
				{
					this._DescriptionLabel = value;
					this.OnPropertyChanged("DescriptionLabel");
				}
			}
		}

		private string _WriteEmailTextLabel = string.Empty;

		public string WriteEmailTextLabel
		{
			get
			{
				return this._WriteEmailTextLabel;
			}

			set
			{
				if (this._WriteEmailTextLabel != value)
				{
					this._WriteEmailTextLabel = value;
					this.OnPropertyChanged("WriteEmailTextLabel");
				}
			}
		}

		private string _RateAppTextLabel = string.Empty;

		public string RateAppTextLabel
		{
			get
			{
				return this._RateAppTextLabel;
			}

			set
			{
				if (this._RateAppTextLabel != value)
				{
					this._RateAppTextLabel = value;
					this.OnPropertyChanged("RateAppTextLabel");
				}
			}
		}

		private string _RateAppBtnLabel = string.Empty;

		public string RateAppBtnLabel
		{
			get
			{
				return this._RateAppBtnLabel;
			}

			set
			{
				if (this._RateAppBtnLabel != value)
				{
					this._RateAppBtnLabel = value;
					this.OnPropertyChanged("RateAppBtnLabel");
				}
			}
		}

		private string _WriteEmailBtnLabel = string.Empty;

		public string WriteEmailBtnLabel
		{
			get
			{
				return this._WriteEmailBtnLabel;
			}

			set
			{
				if (this._WriteEmailBtnLabel != value)
				{
					this._WriteEmailBtnLabel = value;
					this.OnPropertyChanged("WriteEmailBtnLabel");
				}
			}
		}

		private string _DontMakeBadVoteTitleLabel = string.Empty;

		public string DontMakeBadVoteTitleLabel
		{
			get
			{
				return this._DontMakeBadVoteTitleLabel;
			}

			set
			{
				if (this._DontMakeBadVoteTitleLabel != value)
				{
					this._DontMakeBadVoteTitleLabel = value;
					this.OnPropertyChanged("DontMakeBadVoteTitleLabel");
				}
			}
		}

		private string _DontMakeBadVoteTextLabel = string.Empty;

		public string DontMakeBadVoteTextLabel
		{
			get
			{
				return this._DontMakeBadVoteTextLabel;
			}

			set
			{
				if (this._DontMakeBadVoteTextLabel != value)
				{
					this._DontMakeBadVoteTextLabel = value;
					this.OnPropertyChanged("DontMakeBadVoteTextLabel");
				}
			}
		}

		private string _ThankYouVoteLabel = string.Empty;

		public string ThankYouVoteLabel
		{
			get
			{
				return this._ThankYouVoteLabel;
			}

			set
			{
				if (this._ThankYouVoteLabel != value)
				{
					this._ThankYouVoteLabel = value;
					this.OnPropertyChanged("ThankYouVoteLabel");
				}
			}
		}

		private System.Windows.Media.ImageSource _AboutLogo = null;

		public System.Windows.Media.ImageSource AboutLogo
		{
			get
			{
				return this._AboutLogo;
			}

			set
			{
				if (this._AboutLogo != value)
				{
					this._AboutLogo = value;
					this.OnPropertyChanged("AboutLogo");
				}
			}
		}
	}
#endif
}
