//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foodler.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppBarLabels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppBarLabels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Foodler.Resources.AppBarLabels", typeof(AppBarLabels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ate range.
        /// </summary>
        internal static string AddFoodPage_AteRangeOff {
            get {
                return ResourceManager.GetString("AddFoodPage_AteRangeOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ate range.
        /// </summary>
        internal static string AddFoodPage_AteRangeOn {
            get {
                return ResourceManager.GetString("AddFoodPage_AteRangeOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to done.
        /// </summary>
        internal static string AddFoodPage_Done {
            get {
                return ResourceManager.GetString("AddFoodPage_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reset all.
        /// </summary>
        internal static string AddFoodPage_ResetAll {
            get {
                return ResourceManager.GetString("AddFoodPage_ResetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select all.
        /// </summary>
        internal static string AddFoodPage_SelectAll {
            get {
                return ResourceManager.GetString("AddFoodPage_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add me.
        /// </summary>
        internal static string AddParticipantsPage_AddMe {
            get {
                return ResourceManager.GetString("AddParticipantsPage_AddMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to anonymous.
        /// </summary>
        internal static string AddParticipantsPage_AvailableAnonymous {
            get {
                return ResourceManager.GetString("AddParticipantsPage_AvailableAnonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to done.
        /// </summary>
        internal static string AddParticipantsPage_AvailableDone {
            get {
                return ResourceManager.GetString("AddParticipantsPage_AvailableDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unselect all.
        /// </summary>
        internal static string AddParticipantsPage_AvailableUnselectAll {
            get {
                return ResourceManager.GetString("AddParticipantsPage_AvailableUnselectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update contacts.
        /// </summary>
        internal static string AddParticipantsPage_AvailableUpdateContacts {
            get {
                return ResourceManager.GetString("AddParticipantsPage_AvailableUpdateContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        internal static string MainPage_FoodAdd {
            get {
                return ResourceManager.GetString("MainPage_FoodAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to collapse all.
        /// </summary>
        internal static string MainPage_FoodCollapseAll {
            get {
                return ResourceManager.GetString("MainPage_FoodCollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expand all.
        /// </summary>
        internal static string MainPage_FoodExpandAll {
            get {
                return ResourceManager.GetString("MainPage_FoodExpandAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next.
        /// </summary>
        internal static string MainPage_FoodNext {
            get {
                return ResourceManager.GetString("MainPage_FoodNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        internal static string MainPage_ParticipantsAdd {
            get {
                return ResourceManager.GetString("MainPage_ParticipantsAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next.
        /// </summary>
        internal static string MainPage_ParticipantsNext {
            get {
                return ResourceManager.GetString("MainPage_ParticipantsNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to how to use?.
        /// </summary>
        internal static string MainPage_ShowTutorial {
            get {
                return ResourceManager.GetString("MainPage_ShowTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to collapse all.
        /// </summary>
        internal static string MainPage_SumCollapseAll {
            get {
                return ResourceManager.GetString("MainPage_SumCollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expand all.
        /// </summary>
        internal static string MainPage_SumExpandAll {
            get {
                return ResourceManager.GetString("MainPage_SumExpandAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to restart.
        /// </summary>
        internal static string MainPage_SumRestart {
            get {
                return ResourceManager.GetString("MainPage_SumRestart", resourceCulture);
            }
        }
    }
}
