//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foodler.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Images {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Images() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Foodler.Resources.Images", typeof(Images).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Assets/Icon/food/beer.png.
        /// </summary>
        internal static string FoodBeer {
            get {
                return ResourceManager.GetString("FoodBeer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Assets/Icon/food/cake.png.
        /// </summary>
        internal static string FoodCake {
            get {
                return ResourceManager.GetString("FoodCake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Assets/Icon/food/champain.png.
        /// </summary>
        internal static string FoodChampain {
            get {
                return ResourceManager.GetString("FoodChampain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Assets/Icon/food/cocktail.png.
        /// </summary>
        internal static string FoodCocktail {
            get {
                return ResourceManager.GetString("FoodCocktail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Assets/Icon/food/coffe.png.
        /// </summary>
        internal static string FoodCoffe {
            get {
                return ResourceManager.GetString("FoodCoffe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Assets/Icon/food/fast-food.png.
        /// </summary>
        internal static string FoodFastFood {
            get {
                return ResourceManager.GetString("FoodFastFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Assets/Icon/food/fries.png.
        /// </summary>
        internal static string FoodFries {
            get {
                return ResourceManager.GetString("FoodFries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Assets/Icon/food/fruit.png.
        /// </summary>
        internal static string FoodFruit {
            get {
                return ResourceManager.GetString("FoodFruit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Assets/Icon/food/healthy-food.png.
        /// </summary>
        internal static string FoodHealthyFood {
            get {
                return ResourceManager.GetString("FoodHealthyFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Assets/Icon/food/ice-cream.png.
        /// </summary>
        internal static string FoodIceCream {
            get {
                return ResourceManager.GetString("FoodIceCream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Assets/Icon/food/pizza.png.
        /// </summary>
        internal static string FoodPizza {
            get {
                return ResourceManager.GetString("FoodPizza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Assets/Icon/food/refreshments.png.
        /// </summary>
        internal static string FoodRefreshments {
            get {
                return ResourceManager.GetString("FoodRefreshments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Assets/Icon/food/seafood.png.
        /// </summary>
        internal static string FoodSeafood {
            get {
                return ResourceManager.GetString("FoodSeafood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Assets/Icon/food/snack.png.
        /// </summary>
        internal static string FoodSnack {
            get {
                return ResourceManager.GetString("FoodSnack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Assets/Icon/food/soup.png.
        /// </summary>
        internal static string FoodSoup {
            get {
                return ResourceManager.GetString("FoodSoup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Assets/Icon/food/sushi.png.
        /// </summary>
        internal static string FoodSushi {
            get {
                return ResourceManager.GetString("FoodSushi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Assets/Icon/food/vine.png.
        /// </summary>
        internal static string FoodVine {
            get {
                return ResourceManager.GetString("FoodVine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Assets/Icon/animals/non-stroked/bird.png.
        /// </summary>
        internal static string NonStrokedBird {
            get {
                return ResourceManager.GetString("NonStrokedBird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Assets/Icon/animals/non-stroked/cat.png.
        /// </summary>
        internal static string NonStrokedCat {
            get {
                return ResourceManager.GetString("NonStrokedCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Assets/Icon/animals/non-stroked/fish.png.
        /// </summary>
        internal static string NonStrokedFish {
            get {
                return ResourceManager.GetString("NonStrokedFish", resourceCulture);
            }
        }
    }
}
