//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foodler.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Images {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Images() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Foodler.Resources.Images", typeof(Images).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets/Icon/Animals/NonStroked/bird.png
        ///Assets/Icon/Animals/NonStroked/bull.png
        ///Assets/Icon/Animals/NonStroked/cat.png
        ///Assets/Icon/Animals/NonStroked/cow.png
        ///Assets/Icon/Animals/NonStroked/dog.png
        ///Assets/Icon/Animals/NonStroked/duck.png
        ///Assets/Icon/Animals/NonStroked/elephant.png
        ///Assets/Icon/Animals/NonStroked/fish.png
        ///Assets/Icon/Animals/NonStroked/horse.png
        ///Assets/Icon/Animals/NonStroked/ladybug.png
        ///Assets/Icon/Animals/NonStroked/leopard.png
        ///Assets/Icon/Animals/NonStroked/lion.png
        ///Assets/Icon/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AnimalsNonStroked {
            get {
                return ResourceManager.GetString("AnimalsNonStroked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Assets/Icon/Animals/Stroked/bird.png
        ////Assets/Icon/Animals/Stroked/bull.png
        ////Assets/Icon/Animals/Stroked/cat.png
        ////Assets/Icon/Animals/Stroked/cow.png
        ////Assets/Icon/Animals/Stroked/dog.png
        ////Assets/Icon/Animals/Stroked/duck.png
        ////Assets/Icon/Animals/Stroked/elephant.png
        ////Assets/Icon/Animals/Stroked/fish.png
        ////Assets/Icon/Animals/Stroked/horse.png
        ////Assets/Icon/Animals/Stroked/ladybug.png
        ////Assets/Icon/Animals/Stroked/leopard.png
        ////Assets/Icon/Animals/Stroked/lion.png
        ////Assets/Icon/Animals/Stroked/lobster [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AnimalsStroked {
            get {
                return ResourceManager.GetString("AnimalsStroked", resourceCulture);
            }
        }
    }
}
