//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foodler.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Foodler.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you don&apos;t like something in the app, just write me an email, and help to make this app better. Do you still wanna rate app?.
        /// </summary>
        internal static string AboutPage_DontVoteBadlyText {
            get {
                return ResourceManager.GetString("AboutPage_DontVoteBadlyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string AboutPage_InfoHeader {
            get {
                return ResourceManager.GetString("AboutPage_InfoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your vote!.
        /// </summary>
        internal static string AboutPage_ThankYouVote {
            get {
                return ResourceManager.GetString("AboutPage_ThankYouVote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Data.
        /// </summary>
        internal static string AddFoodPage_InvalidDataHeader {
            get {
                return ResourceManager.GetString("AddFoodPage_InvalidDataHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should enter the price, and select at least one participant..
        /// </summary>
        internal static string AddFoodPage_InvalidDataMessage {
            get {
                return ResourceManager.GetString("AddFoodPage_InvalidDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can add anonymous only in full version of the app. Would you like to get a full version?.
        /// </summary>
        internal static string AddParticipantsPage_AnonymousAvailableOnFullVersionMessage {
            get {
                return ResourceManager.GetString("AddParticipantsPage_AnonymousAvailableOnFullVersionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Data.
        /// </summary>
        internal static string AddParticipantsPage_InvalidDataHeader {
            get {
                return ResourceManager.GetString("AddParticipantsPage_InvalidDataHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should enter at least two participants..
        /// </summary>
        internal static string AddParticipantsPage_InvalidDataMessage {
            get {
                return ResourceManager.GetString("AddParticipantsPage_InvalidDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can add only {0} participants in the light version. Would you like to get a full version without any limitation?.
        /// </summary>
        internal static string AddParticipantsPage_ParticipantsLimitMessage {
            get {
                return ResourceManager.GetString("AddParticipantsPage_ParticipantsLimitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        internal static string Common_AttentionHeader {
            get {
                return ResourceManager.GetString("Common_AttentionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unavailable.
        /// </summary>
        internal static string Common_UnavailableFunctionalityHeader {
            get {
                return ResourceManager.GetString("Common_UnavailableFunctionalityHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you like the app?.
        /// </summary>
        internal static string MainPage_DoYouLikeApp {
            get {
                return ResourceManager.GetString("MainPage_DoYouLikeApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        internal static string MainPage_FeedbackHeader {
            get {
                return ResourceManager.GetString("MainPage_FeedbackHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send me an email with a description of what you do not like, and may already be in the next version of your wishes will be taken into account. Send a letter?.
        /// </summary>
        internal static string MainPage_FeedbackSendEmail {
            get {
                return ResourceManager.GetString("MainPage_FeedbackSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can add only {0} food items in the light version. Would you like to get a full version without any limitation?.
        /// </summary>
        internal static string MainPage_FoodTabFoodLimitMessage {
            get {
                return ResourceManager.GetString("MainPage_FoodTabFoodLimitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participants should be added first..
        /// </summary>
        internal static string MainPage_NoParticipantsMessage {
            get {
                return ResourceManager.GetString("MainPage_NoParticipantsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please rate the app, it does not take much time. \ nGo to the assessment?.
        /// </summary>
        internal static string MainPage_PleaseRateApp {
            get {
                return ResourceManager.GetString("MainPage_PleaseRateApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        internal static string MainPage_RateHeader {
            get {
                return ResourceManager.GetString("MainPage_RateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will reset all your changes. Continue?.
        /// </summary>
        internal static string MainPage_SumTabResetMessage {
            get {
                return ResourceManager.GetString("MainPage_SumTabResetMessage", resourceCulture);
            }
        }
    }
}
