//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foodler.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UILabels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UILabels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Foodler.Resources.UILabels", typeof(UILabels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to male.
        /// </summary>
        internal static string AddAnonymousParticipantPage_MaleTabHeader {
            get {
                return ResourceManager.GetString("AddAnonymousParticipantPage_MaleTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to female.
        /// </summary>
        internal static string AddAnonymousParticipantPageFemaleTabHeader {
            get {
                return ResourceManager.GetString("AddAnonymousParticipantPageFemaleTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your food.
        /// </summary>
        internal static string AddFoodPage_ChooseFoodHeader {
            get {
                return ResourceManager.GetString("AddFoodPage_ChooseFoodHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food:.
        /// </summary>
        internal static string AddFoodPage_FoodTitle {
            get {
                return ResourceManager.GetString("AddFoodPage_FoodTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participants:.
        /// </summary>
        internal static string AddFoodPage_ParticipantsTitle {
            get {
                return ResourceManager.GetString("AddFoodPage_ParticipantsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price:.
        /// </summary>
        internal static string AddFoodPage_PriceTitle {
            get {
                return ResourceManager.GetString("AddFoodPage_PriceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to available.
        /// </summary>
        internal static string AddParticipantsPage_AvailableTabHeader {
            get {
                return ResourceManager.GetString("AddParticipantsPage_AvailableTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selected.
        /// </summary>
        internal static string AddParticipantsPage_SelectedTabHeader {
            get {
                return ResourceManager.GetString("AddParticipantsPage_SelectedTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foodler.
        /// </summary>
        internal static string Common_AppName {
            get {
                return ResourceManager.GetString("Common_AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participants:.
        /// </summary>
        internal static string Controls_FoodExpanderParticipants {
            get {
                return ResourceManager.GetString("Controls_FoodExpanderParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price: .
        /// </summary>
        internal static string Controls_FoodExpanderPrice {
            get {
                return ResourceManager.GetString("Controls_FoodExpanderPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalParticipants.
        /// </summary>
        internal static string Controls_FoodExpanderTotalParticipants {
            get {
                return ResourceManager.GetString("Controls_FoodExpanderTotalParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food eaten:.
        /// </summary>
        internal static string Controls_ParticipantsExpanderTotalEaten {
            get {
                return ResourceManager.GetString("Controls_ParticipantsExpanderTotalEaten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beer.
        /// </summary>
        internal static string FoodName_Beer {
            get {
                return ResourceManager.GetString("FoodName_Beer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cake.
        /// </summary>
        internal static string FoodName_Cake {
            get {
                return ResourceManager.GetString("FoodName_Cake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Champagne.
        /// </summary>
        internal static string FoodName_Champagne {
            get {
                return ResourceManager.GetString("FoodName_Champagne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cocktail.
        /// </summary>
        internal static string FoodName_Cocktail {
            get {
                return ResourceManager.GetString("FoodName_Cocktail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coffe.
        /// </summary>
        internal static string FoodName_Coffe {
            get {
                return ResourceManager.GetString("FoodName_Coffe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast food.
        /// </summary>
        internal static string FoodName_FastFood {
            get {
                return ResourceManager.GetString("FoodName_FastFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First dishes.
        /// </summary>
        internal static string FoodName_FirstDishes {
            get {
                return ResourceManager.GetString("FoodName_FirstDishes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fruit.
        /// </summary>
        internal static string FoodName_Fruit {
            get {
                return ResourceManager.GetString("FoodName_Fruit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healthy food.
        /// </summary>
        internal static string FoodName_HealthyFood {
            get {
                return ResourceManager.GetString("FoodName_HealthyFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice cream.
        /// </summary>
        internal static string FoodName_IceCream {
            get {
                return ResourceManager.GetString("FoodName_IceCream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pizza.
        /// </summary>
        internal static string FoodName_Pizza {
            get {
                return ResourceManager.GetString("FoodName_Pizza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshments.
        /// </summary>
        internal static string FoodName_Refreshments {
            get {
                return ResourceManager.GetString("FoodName_Refreshments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seafood.
        /// </summary>
        internal static string FoodName_Seafood {
            get {
                return ResourceManager.GetString("FoodName_Seafood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snacks.
        /// </summary>
        internal static string FoodName_Snacks {
            get {
                return ResourceManager.GetString("FoodName_Snacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sushi.
        /// </summary>
        internal static string FoodName_Sushi {
            get {
                return ResourceManager.GetString("FoodName_Sushi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vine.
        /// </summary>
        internal static string FoodName_Vine {
            get {
                return ResourceManager.GetString("FoodName_Vine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to food price.
        /// </summary>
        internal static string InputFoodPricePage_FoodPrice {
            get {
                return ResourceManager.GetString("InputFoodPricePage_FoodPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to food.
        /// </summary>
        internal static string MainPage_FoodTabHeader {
            get {
                return ResourceManager.GetString("MainPage_FoodTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no food, add some..
        /// </summary>
        internal static string MainPage_NoFoodHint {
            get {
                return ResourceManager.GetString("MainPage_NoFoodHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no participants,        ///add some..
        /// </summary>
        internal static string MainPage_NoParticipantsHint {
            get {
                return ResourceManager.GetString("MainPage_NoParticipantsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should add some         ///participants and food first.        ///Come back here after..
        /// </summary>
        internal static string MainPage_NoSummaryHint {
            get {
                return ResourceManager.GetString("MainPage_NoSummaryHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to participants.
        /// </summary>
        internal static string MainPage_ParticipantsTabHeader {
            get {
                return ResourceManager.GetString("MainPage_ParticipantsTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sum.
        /// </summary>
        internal static string MainPage_SummaryTabHeader {
            get {
                return ResourceManager.GetString("MainPage_SummaryTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total:.
        /// </summary>
        internal static string MainPage_TotalSum {
            get {
                return ResourceManager.GetString("MainPage_TotalSum", resourceCulture);
            }
        }
    }
}
